export const todos_produtos = [
  {
    nome: 'Praesent auctor',
    preco: '42.49',
    img: 'img1.webp',
    categoria: 'flores',
    cor: 'laranja'
  },
  {
    nome: 'Duis commodo',
    preco: '24.99',
    img: 'img2.webp',
    categoria: 'flores',
    cor: 'vermelho',
  },
  {
    nome: 'Ligula ipsum',
    preco: '22.25',
    img: 'img3.webp',
    categoria: 'flores',
    cor: 'amarelo',

  },
  {
    nome: 'Quisque',
    preco: '36.49',
    img: 'img4.webp',
    categoria: 'cactos',
    cor: 'verde',

  },
  {
    nome: 'Maecenas elementum',
    preco: '27.79',
    img: 'img5.webp',
    categoria: 'cactos',
    cor: 'verde',
  },
  {
    nome: 'Phasellus mattis',
    preco: '51.49',
    img: 'img6.webp',
    categoria: 'flores',
    cor: 'roxo',

  },
  {
    nome: 'Curabitur',
    preco: '12.25',
    img: 'img7.webp',
    categoria: 'outros',
    cor: 'verde'
  },
  {
    nome: 'Donec placerat',
    preco: '25.99',
    img: 'img8.webp',
    categoria: 'flores',
    cor: 'rosa',
  },
  {
    nome: 'Orci varius',
    preco: '42.75',
    img: 'img9.webp',
    categoria: 'flores',
    cor: 'branco',
  },
  {
    nome: 'Cras sit',
    preco: '75.10',
    img: 'img10.webp',
    categoria: 'flores',
    cor: 'azul',
  },
  {
    nome: 'Etiam',
    preco: '17.45',
    img: 'img11.webp',
    categoria: 'cactos',
    cor: 'verde',
  },
  {
    nome: 'Ullamcorper augue',
    preco: '38.25',
    img: 'img12.webp',
    categoria: 'flores',
    cor: 'rosa',
  },
  {
    nome: 'Eget facilisis',
    preco: '48.60',
    img: 'img13.webp',
    categoria: 'outros',
    cor: 'verde',
  },
  {
    nome: 'Viverra',
    preco: '29.15',
    img: 'img14.webp',
    categoria: 'outros',
    cor: 'verde',
  },
  {
    nome: 'Dapibus',
    preco: '57.99',
    img: 'img15.webp',
    categoria: 'flores',
    cor: 'laranja',
  },
  {
    nome: 'Fusce ac lacus',
    preco: '84.49',
    img: 'img16.webp',
    categoria: 'flores',
    cor: 'vermelho',
  },
  {
    nome: 'Sed consequat',
    preco: '129.99',
    img: 'img17.webp',
    categoria: 'outros',
    cor: 'verde',
  },
  {
    nome: 'Vitae scelerisque',
    preco: '37.25',
    img: 'img18.webp',
    categoria: 'cactos',
    cor: 'vermelho',
  },
  {
    nome: 'Aenean',
    preco: '73.19',
    img: 'img19.webp',
    categoria: 'flores',
    cor: 'rosa',
  },
  {
    nome: 'Nunc leo',
    preco: '34.99',
    img: 'img20.webp',
    categoria: 'outros',
    cor: 'verde',
  },
  {
    nome: 'Diam rutrum',
    preco: '58.49',
    img: 'img21.webp',
    categoria: 'flores',
    cor: 'roxo',
  },
  {
    nome: 'Quam lectus',
    preco: '48.49',
    img: 'img22.webp',
    categoria: 'cactos',
    cor: 'verde',
  },
  {
    nome: 'Magna',
    preco: '76.15',
    img: 'img23.webp',
    categoria: 'cactos',
    cor: 'verde',
  },
  {
    nome: 'Blandit',
    preco: '34.99',
    img: 'img24.webp',
    categoria: 'cactos',
    cor: 'rosa',
  },
  {
    nome: 'Pharetra auctor',
    preco: '94.49',
    img: 'img25.webp',
    categoria: 'flores',
    cor: 'rosa',
  },
  {
    nome: 'Porttitor',
    preco: '22.99',
    img: 'img26.webp',
    categoria: 'flores',
    cor: 'amarelo',
  },
  {
    nome: 'Cras posuere',
    preco: '68.49',
    img: 'img27.webp',
    categoria: 'flores',
    cor: 'vermelho',
  },
  {
    nome: 'Orci ',
    preco: '25.00',
    img: 'img28.webp',
    categoria: 'outros',
    cor: 'verde',
  },
  {
    nome: 'Lacinia finibus',
    preco: '67.75',
    img: 'img29.webp',
    categoria: 'flores',
    cor: 'roxo',
  },
  {
    nome: 'Convallis',
    preco: '26.99',
    img: 'img30.webp',
    categoria: 'flores',
    cor: 'branco',
  },
  {
    nome: 'Iaculis',
    preco: '38.55',
    img: 'img31.webp',
    categoria: 'cactos',
    cor: 'verde',
  },
  {
    nome: 'Ultricies',
    preco: '45.49',
    img: 'img32.webp',
    categoria: 'flores',
    cor: 'azul',
  }
]