export const all_products = [
  {
    nome: "Praesent auctor",
    preco: "42.49",
    img: "img1.webp",
    categoria: "flores",
    cor: "rosa",
    description: "Cras quis nunc consectetur ex tristique posuere.",
  },
  {
    nome: "Duis commodo",
    preco: "24.99",
    img: "img2.webp",
    categoria: "flores",
    cor: "roxo",
    description:
      "Vestibulum eget placerat mauris. Ut quis commodo tortor, a iaculis metus.",
  },
  {
    nome: "Ligula ipsum",
    preco: "22.25",
    img: "img3.webp",
    categoria: "flores",
    cor: "amarelo",
    description:
      "Aliquam accumsan mollis quam sed dictum. Duis eget malesuada nisi.",
  },
  {
    nome: "Quisque",
    preco: "36.49",
    img: "img4.webp",
    categoria: "cactos",
    cor: "verde",
    description:
      "Vestibulum eget placerat mauris. Ut quis commodo tortor, a iaculis metus.",
  },
  {
    nome: "Maecenas elementum",
    preco: "27.79",
    img: "img5.webp",
    categoria: "cactos",
    description: "Cras quis nunc consectetur ex tristique posuere.",
    cor: "verde",
  },
  {
    nome: "Phasellus mattis",
    preco: "51.49",
    img: "img6.webp",
    categoria: "flores",
    cor: "roxo",
    description:
      "Aliquam accumsan mollis quam sed dictum. Duis eget malesuada nisi.",
  },
  {
    nome: "Curabitur",
    preco: "12.25",
    img: "img7.webp",
    categoria: "outros",
    cor: "verde",
    description:
      "Vestibulum eget placerat mauris. Ut quis commodo tortor, a iaculis metus.",
  },
  {
    nome: "Donec placerat",
    preco: "25.99",
    img: "img8.webp",
    categoria: "flores",
    description: "Cras quis nunc consectetur ex tristique posuere.",
    cor: "rosa",
  },
  {
    nome: "Orci varius",
    preco: "42.75",
    img: "img9.webp",
    categoria: "flores",
    cor: "branco",
    description:
      "Aliquam accumsan mollis quam sed dictum. Duis eget malesuada nisi.",
  },
  {
    nome: "Cras sit",
    preco: "75.10",
    img: "img10.webp",
    categoria: "flores",
    cor: "azul",
    description:
      "Aliquam accumsan mollis quam sed dictum. Duis eget malesuada nisi.",
  },
  {
    nome: "Etiam",
    preco: "17.45",
    img: "img11.webp",
    categoria: "cactos",
    description: "Cras quis nunc consectetur ex tristique posuere.",
    cor: "verde",
  },
  {
    nome: "Ullamcorper augue",
    preco: "38.25",
    img: "img12.webp",
    categoria: "flores",
    description: "Cras quis nunc consectetur ex tristique posuere.",
    cor: "laranja",
  },
  {
    nome: "Eget facilisis",
    preco: "48.60",
    img: "img13.webp",
    categoria: "outros",
    cor: "verde",
    description:
      "Aliquam accumsan mollis quam sed dictum. Duis eget malesuada nisi.",
  },
  {
    nome: "Viverra",
    preco: "29.15",
    img: "img14.webp",
    categoria: "outros",
    cor: "verde",
    description:
      "Vestibulum eget placerat mauris. Ut quis commodo tortor, a iaculis metus.",
  },
  {
    nome: "Dapibus",
    preco: "57.99",
    img: "img15.webp",
    categoria: "flores",
    cor: "laranja",
    description:
      "Aliquam accumsan mollis quam sed dictum. Duis eget malesuada nisi.",
  },
  {
    nome: "Fusce ac lacus",
    preco: "84.49",
    img: "img16.webp",
    categoria: "flores",
    cor: "vermelho",
    description:
      "Aliquam accumsan mollis quam sed dictum. Duis eget malesuada nisi.",
  },
  {
    nome: "Sed consequat",
    preco: "129.99",
    img: "img17.webp",
    categoria: "outros",
    cor: "verde",
    description:
      "Vestibulum eget placerat mauris. Ut quis commodo tortor, a iaculis metus.",
  },
  {
    nome: "Vitae scelerisque",
    preco: "37.25",
    img: "img18.webp",
    categoria: "cactos",
    description: "Cras quis nunc consectetur ex tristique posuere.",
    cor: "vermelho",
  },
  {
    nome: "Aenean",
    preco: "73.19",
    img: "img19.webp",
    categoria: "flores",
    cor: "rosa",
    description:
      "Aliquam accumsan mollis quam sed dictum. Duis eget malesuada nisi.",
  },
  {
    nome: "Nunc leo",
    preco: "34.99",
    img: "img20.webp",
    categoria: "outros",
    description: "Cras quis nunc consectetur ex tristique posuere.",
    cor: "verde",
  },
  {
    nome: "Diam rutrum",
    preco: "58.49",
    img: "img21.webp",
    description: "Cras quis nunc consectetur ex tristique posuere.",
    categoria: "flores",
    cor: "roxo",
  },
  {
    nome: "Quam lectus",
    preco: "48.49",
    img: "img22.webp",
    description: "Cras quis nunc consectetur ex tristique posuere.",
    categoria: "cactos",
    cor: "verde",
  },
  {
    nome: "Magna",
    preco: "76.15",
    img: "img23.webp",
    categoria: "cactos",
    cor: "verde",
    description:
      "Vestibulum eget placerat mauris. Ut quis commodo tortor, a iaculis metus.",
  },
  {
    nome: "Blandit",
    preco: "34.99",
    img: "img24.webp",
    categoria: "cactos",
    description: "Cras quis nunc consectetur ex tristique posuere.",
    cor: "rosa",
  },
  {
    nome: "Pharetra auctor",
    preco: "94.49",
    img: "img25.webp",
    categoria: "flores",
    cor: "rosa",
    description:
      "Aliquam accumsan mollis quam sed dictum. Duis eget malesuada nisi.",
  },
  {
    nome: "Porttitor",
    preco: "22.99",
    img: "img26.webp",
    categoria: "flores",
    cor: "amarelo",
    description:
      "Vestibulum eget placerat mauris. Ut quis commodo tortor, a iaculis metus.",
  },
  {
    nome: "Cras posuere",
    preco: "68.49",
    img: "img27.webp",
    categoria: "flores",
    description: "Cras quis nunc consectetur ex tristique posuere.",
    cor: "vermelho",
  },
  {
    nome: "Orci ",
    preco: "25.00",
    img: "img28.webp",
    categoria: "outros",
    cor: "verde",
    description:
      "Aliquam accumsan mollis quam sed dictum. Duis eget malesuada nisi.",
  },
  {
    nome: "Lacinia finibus",
    preco: "67.75",
    img: "img29.webp",
    categoria: "flores",
    description: "Cras quis nunc consectetur ex tristique posuere.",
    cor: "roxo",
  },
  {
    nome: "Convallis",
    preco: "26.99",
    img: "img30.webp",
    categoria: "flores",
    cor: "branco",
    description:
      "Vestibulum eget placerat mauris. Ut quis commodo tortor, a iaculis metus.",
  },
  {
    nome: "Iaculis",
    preco: "38.55",
    img: "img31.webp",
    categoria: "cactos",
    cor: "verde",
    description:
      "Aliquam accumsan mollis quam sed dictum. Duis eget malesuada nisi.",
  },
  {
    nome: "Ultricies",
    preco: "36.49",
    img: "img32.webp",
    categoria: "flores",
    description: "Cras quis nunc consectetur ex tristique posuere.",
    cor: "azul",
  },
  {
    nome: "Tortor eget",
    preco: "36.49",
    img: "img33.webp",
    categoria: "cactos",
    cor: "verde",
    description:
      "Vestibulum eget placerat mauris. Ut quis commodo tortor, a iaculis metus.",
  },
  {
    nome: "Class aptent",
    preco: "85.49",
    img: "img34.webp",
    categoria: "flores",
    cor: "rosa",
    description:
      "Aliquam accumsan mollis quam sed dictum. Duis eget malesuada nisi.",
  },
  {
    nome: "Tincidunt ",
    preco: "19.99",
    img: "img35.webp",
    categoria: "outros",
    description: "Cras quis nunc consectetur ex tristique posuere.",
    cor: "verde",
  },
  {
    nome: "Risus rutrum",
    preco: "57.25",
    img: "img36.webp",
    categoria: "flores",
    cor: "rosa",
    description:
      "Vestibulum eget placerat mauris. Ut quis commodo tortor, a iaculis metus.",
  },
  {
    nome: "Egestas",
    preco: "32.15",
    img: "img37.webp",
    categoria: "flores",
    cor: "vermelho",
    description:
      "Vestibulum eget placerat mauris. Ut quis commodo tortor, a iaculis metus.",
  },
  {
    nome: "Duis nisi ",
    preco: "27.49",
    img: "img38.webp",
    categoria: "flores",
    description: "Cras quis nunc consectetur ex tristique posuere.",
    cor: "branco",
  },
  {
    nome: "Accumsan",
    preco: "49.99",
    img: "img39.webp",
    categoria: "flores",
    cor: "laranja",
    description:
      "Vestibulum eget placerat mauris. Ut quis commodo tortor, a iaculis metus.",
  },
];
